/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package echoserver.app;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        EchoServer classUnderTest = new EchoServer();
    }
}
